### ISSUE TITLE
Add Google Adsense support

### ISSUE THREAD

**Issue by gopaldas958** [dentonzh/Eggspress#61]
Please add Google Adsense support for the blogs

**Comment by dentonzh** [comment]
Thanks for the request, @gopaldas958.  I'll take a look at this some time in the next week or two, but presently Adsense is not on the roadmap.

The latest merge (https://github.com/dentonzh/Eggspress/pull/60) adds custom components, which you can take advantage of if you know some React. To use it:

- Make sure you're on the lateset version of Eggspress (use Sync Fork in Github's web interface)
- Create a folder called `my_components` inside of your workspace (along side `my_posts`, `my_pages`, etc.)
- Create a component file, e.g. `Adsense.tsx`
- If you're using dependencies, list them in comma-separated string in the first line of your component file (e.g. `// chart.js, react-chartjs-2`)
- In your Markdown content, directly write `<Adsense />`

I do have plans for adding examples of such components. I will update here if an Adsense component is one of them.
